# Generated by Django 4.2.6 on 2023-11-11 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solvencia',
            old_name='nombre',
            new_name='marca',
        ),
        migrations.AddField(
            model_name='solvencia',
            name='bien_nacional',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='solvencia',
            name='descripcion',
            field=models.CharField(default='No asignado', max_length=100),
        ),
        migrations.AddField(
            model_name='solvencia',
            name='modelo',
            field=models.CharField(default='No asignado', max_length=50),
        ),
        migrations.AddField(
            model_name='solvencia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.empleado'),
        ),
    ]
