# Generated by Django 4.2.6 on 2023-11-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_perifericos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perifericos',
            new_name='Periferico',
        ),
    ]
